//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.03 at 03:05:14 PM ICT 
//


package com.airplane.vna.schemas.ticket;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.airplane.vna.schemas.ticket package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.airplane.vna.schemas.ticket
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TicketDetailsRequest }
     * 
     */
    public TicketDetailsRequest createTicketDetailsRequest() {
        return new TicketDetailsRequest();
    }

    /**
     * Create an instance of {@link TicketDetailsResponse }
     * 
     */
    public TicketDetailsResponse createTicketDetailsResponse() {
        return new TicketDetailsResponse();
    }

    /**
     * Create an instance of {@link Ticket }
     * 
     */
    public Ticket createTicket() {
        return new Ticket();
    }

    /**
     * Create an instance of {@link AllTicketRequest }
     * 
     */
    public AllTicketRequest createAllTicketRequest() {
        return new AllTicketRequest();
    }

    /**
     * Create an instance of {@link AllTicketResponse }
     * 
     */
    public AllTicketResponse createAllTicketResponse() {
        return new AllTicketResponse();
    }

    /**
     * Create an instance of {@link CustomList }
     * 
     */
    public CustomList createCustomList() {
        return new CustomList();
    }

    /**
     * Create an instance of {@link OneWayTicketRequest }
     * 
     */
    public OneWayTicketRequest createOneWayTicketRequest() {
        return new OneWayTicketRequest();
    }

    /**
     * Create an instance of {@link OneWayTicketResponse }
     * 
     */
    public OneWayTicketResponse createOneWayTicketResponse() {
        return new OneWayTicketResponse();
    }

    /**
     * Create an instance of {@link TwoWayTicketRequest }
     * 
     */
    public TwoWayTicketRequest createTwoWayTicketRequest() {
        return new TwoWayTicketRequest();
    }

    /**
     * Create an instance of {@link TwoWayTicketResponse }
     * 
     */
    public TwoWayTicketResponse createTwoWayTicketResponse() {
        return new TwoWayTicketResponse();
    }

}
