//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.03 at 09:36:45 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "entity.ticket.vna.airplane.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.airplane.vna.ticket.entity;
